apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-svc
  name: sample-svc
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ports:
  - name: "application-port"
    port: 443
    protocol: TCP
    targetPort: 80
  selector:
    app: sample-deploy-label
  type: ClusterIP
